### ISSUE TITLE
Problem with docker build

### ISSUE THREAD

**Issue by vanhpham** [Renbago/autonomus_vehicle#6]
Hi, something went wrong went i run the docker-compose build --no-cache, i clone the repo into my folder and then cd to docker/ and then run the docker_compose build but this went up:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.autonomous_ws: 'device_cgroup_rules'
services.autonomous_ws.volumes contains an invalid type, it should be a string
services.autonomous_ws.volumes contains an invalid type, it should be a string
services.autonomous_ws.volumes contains an invalid type, it should be a string

```
I'm running on Ubuntu 20.04 with latest docker desktop version.
Anyway thanks for publishing this helpful repo.

**Comment by Renbago** [comment]
Hi, I will be check to problem ASAP thanks for feedback

**Comment by Renbago** [comment]
I believe error is relative with the docker version can you change the version to different like 3.8 from compose yml?

**Comment by Renbago** [comment]
İs  there any issue still? @vanhpham , I will close it if there is no problem.
